project:
  type: website
  output-dir: docs

website: 
  title: "AMP2023"
  navbar:
    background: primary
    left: 
      - href: index.qmd
        text: Home
      - href: registration.qmd
        text: Registration
      - href: schedule.qmd
        text: Schedule
      - href: cfp.qmd
        text: CFP

resources:
  - CNAME