
# Call for Papers

## Submission Guidelines

We invite abstracts for either oral presentation (20 minutes, followed by 10 minutes of discussion) or poster presentation. Abstracts must be anonymous, so please be sure to eliminate any identifying information and metadata from the document. Length is limited to a maximum of <b>two single-spaced pages</b> (US Letter), figures and references included. Font size should be 12-point, with margins of at least one inch (2.54cm) left on all sides. Abstracts must be submitted in .pdf format.

Submissions are limited to two per author, with at most one submission being single- or primary-authored. All submissions must be novel work, not published or accepted at a journal, nor given or scheduled at another conference.

We invite abstracts in any area that bears on the central questions of our discipline, including work based on consultant data, phonological theory, computational phonology, corpus phonology, experimental phonology, neurobiology of language, diachronic change, acquisition, sign language phonology, and the interface of phonology with neighboring disciplines.

The extended deadline for abstract submission is <b>Friday, July 14, 2023 at 11:59 p.m. (Pacific Time)</b>.

We will leave EasyChair access on through the weekend (July 15-16) for those who need a bit of extra time to write their abstract or who want to edit one they have already submitted.

Abstraction submission link: <https://easychair.org/conferences/?conf=amp2023>