---
title: ""
---

The 2023 Annual Meeting on Phonology (AMP 2023) was held online on October 20-22 (not at Johns Hopkins University as originally planned). [AMP](https://blogs.umass.edu/amp-info/), founded in 2013, is held every Fall, and showcases high quality research in all areas of phonology.

## [Schedule (with links to abstracts/handouts/posters/slides)](schedule.qmd)

## Invited speakers

[Ellen Broselow](https://linguistics.stonybrook.edu/faculty/ellen.broselow/) (_Stony Brook University_)

[Laura Gwilliams](https://lauragwilliams.github.io/) (_Stanford University_)

[Jie Zhang](https://linguistics.ku.edu/people/jie-zhang) (_University of Kansas_)

<br/>

# ~~Registration~~

Thanks to everyone who participated in the conference!

<br/>

## Submission info

~~[Call for papers](cfp.qmd) (with extended deadline)~~

~~Abstract submission link: <https://easychair.org/conferences/?conf=amp2023>~~

Thanks to everyone who submitted abstracts and reviewed them!

<br/>

- - -

Any questions about conference organization can be emailed to<br/> <a href="mailto: amp2023jhu@gmail.com"> amp2023jhu@gmail.com</a>.

<br/>

We will post news about AMP on Phonolist. To subscribe, send a message to <a href="mailto: phonolist+subscribe@groups.umass.edu"> phonolist+subscribe@groups.umass.edu<a>.<br/>When you get a confirmation e-mail, reply to it (don’t use the link).
